/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Customer } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface CustomerControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteCustomerById
     * 
     * @param customerId customerId
     */
    deleteCustomerById(customerId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllCustomers
     * 
     */
    getAllCustomers(extraHttpRequestParams?: any): Observable<Array<Customer>>;

    /**
     * getCustomerById
     * 
     * @param customerId customerId
     */
    getCustomerById(customerId: number, extraHttpRequestParams?: any): Observable<Customer>;

    /**
     * saveCustomer
     * 
     * @param customer customer
     */
    saveCustomer(customer: Customer, extraHttpRequestParams?: any): Observable<Customer>;

    /**
     * updateCustomer
     * 
     * @param customer customer
     */
    updateCustomer(customer: Customer, extraHttpRequestParams?: any): Observable<Customer>;

}
