/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Invoice } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface InvoiceControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteInvoiceById
     * 
     * @param invoiceId invoiceId
     */
    deleteInvoiceById(invoiceId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllInvoices
     * 
     */
    getAllInvoices(extraHttpRequestParams?: any): Observable<Array<Invoice>>;

    /**
     * getInvoiceById
     * 
     * @param invoiceId invoiceId
     */
    getInvoiceById(invoiceId: number, extraHttpRequestParams?: any): Observable<Invoice>;

    /**
     * saveInvoice
     * 
     * @param invoice invoice
     */
    saveInvoice(invoice: Invoice, extraHttpRequestParams?: any): Observable<Invoice>;

    /**
     * updateInvoice
     * 
     * @param invoice invoice
     */
    updateInvoice(invoice: Invoice, extraHttpRequestParams?: any): Observable<Invoice>;

}
