/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { InvoiceDetails } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface InvoiceDetailsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteInvoiceDetailsById
     * 
     * @param invoiceDetailId invoiceDetailId
     */
    deleteInvoiceDetailsById(invoiceDetailId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllInvoiceDetailses
     * 
     */
    getAllInvoiceDetailses(extraHttpRequestParams?: any): Observable<Array<InvoiceDetails>>;

    /**
     * getInvoiceDetailsById
     * 
     * @param invoiceDetailId invoiceDetailId
     */
    getInvoiceDetailsById(invoiceDetailId: number, extraHttpRequestParams?: any): Observable<InvoiceDetails>;

    /**
     * saveInvoiceDetails
     * 
     * @param invoiceDetails invoiceDetails
     */
    saveInvoiceDetails(invoiceDetails: InvoiceDetails, extraHttpRequestParams?: any): Observable<InvoiceDetails>;

    /**
     * updateInvoiceDetails
     * 
     * @param invoiceDetails invoiceDetails
     */
    updateInvoiceDetails(invoiceDetails: InvoiceDetails, extraHttpRequestParams?: any): Observable<InvoiceDetails>;

}
