/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProductInvoice } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface ProductInvoiceControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteProductInvoiceById
     * 
     * @param productInvoiceId productInvoiceId
     */
    deleteProductInvoiceById(productInvoiceId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * findByInvoiceId
     * 
     * @param invoiceId invoiceId
     */
    findByInvoiceId(invoiceId: number, extraHttpRequestParams?: any): Observable<Array<ProductInvoice>>;

    /**
     * getAllProductInvoices
     * 
     */
    getAllProductInvoices(extraHttpRequestParams?: any): Observable<Array<ProductInvoice>>;

    /**
     * getProductInvoiceById
     * 
     * @param productInvoiceId productInvoiceId
     */
    getProductInvoiceById(productInvoiceId: number, extraHttpRequestParams?: any): Observable<ProductInvoice>;

    /**
     * saveProductInvoice
     * 
     * @param productInvoice productInvoice
     */
    saveProductInvoice(productInvoice: ProductInvoice, extraHttpRequestParams?: any): Observable<ProductInvoice>;

    /**
     * updateProductInvoice
     * 
     * @param productInvoice productInvoice
     */
    updateProductInvoice(productInvoice: ProductInvoice, extraHttpRequestParams?: any): Observable<ProductInvoice>;

}
