/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceDetails } from './invoice-details';


export interface Invoice { 
    createdDate?: string;
    id?: number;
    invoiceDetailId?: InvoiceDetails;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    recordStatus?: number;
}

