/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Invoice } from './invoice';
import { Product } from './product';


export interface ProductInvoice { 
    createdDate?: string;
    id?: number;
    invoiceId?: Invoice;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    productId?: Product;
    quantity?: number;
    recordStatus?: number;
}

