/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';


export interface Product { 
    category?: Category;
    code?: string;
    description?: string;
    id?: number;
    name?: string;
    price?: number;
    stock?: number;
    unit?: string;
}

