/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';


export interface User { 
    createdDate?: string;
    employeeId?: Employee;
    id?: number;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    password?: string;
    recordStatus?: number;
    username?: string;
}

