/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './granted-authority';


export interface User { 
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
    authorities?: Array<GrantedAuthority>;
    createdDate?: string;
    credentialsNonExpired?: boolean;
    enabled?: boolean;
    id?: number;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    recordStatus?: number;
    username?: string;
}

